### ISSUE TITLE
Real functions

### ISSUE THREAD

**Issue by mdraith** [dmsc/fastbasic#94] opened 2024-07-03 23:21 UTC
Something like this:

```
FUNC FIBONACCI N
  IF N<=1
    RETURN N
  ELSE
    RETURN FN FIBONACCI N-1 + FN FIBONACCI N-2
  ENDIF
ENDFUNC
```

**Comment by dmsc** [comment] 2024-07-27 02:48
Duplicate of #69

**Closed** 2024-07-27 02:52 UTC
Labels: enhancement
